# Generated by Django 4.2.7 on 2023-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
